# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Disabling shallow clone for SonarCloud
    #- name: Set up Python ${{ matrix.python-version }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        #python-version: ${{ matrix.python-version }}
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[develop]'
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov-report=xml
    - name: Collect System details
      run: |
        pwd
        ls -la
        ls -la src/
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=johnbrandborg
          -Dsonar.projectKey=johnbrandborg_restful-client
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.python.version=3
          -Dsonar.sources=src/
          -Dsonar.test.exclusions=tests/**
          -Dsonar.tests=tests/
